name: Release

on:
#  push:
#    paths:
#      - 'VERSION'
#    branches:
#      - main
  pull_request:
    branches: [ "main" ]
#    paths:
#      - 'VERSION'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        id: version
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Build
        run: cargo build --release
      - name: Calculate SHA256
        run: shasum -a 256 target/release/log-inspector | cut -d ' ' -f 1 > sha256.txt
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
      - name: Upload Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/log-inspector
          asset_name: log-inspector
          asset_content_type: application/octet-stream
      - name: Update Formula
        run: |
          git fetch origin
          git checkout -b main origin/main
          SHA256=$(cat sha256.txt)
          VERSION=$(cat VERSION)
          sed -i '' "s/version \".*\"/version \"$VERSION\"/" .homebrew/log-inspector.rb
          sed -i '' "s/sha256 \".*\"/sha256 \"$SHA256\"/" .homebrew/log-inspector.rb
          git add .homebrew/log-inspector.rb
          git commit -m "Update formula to version $VERSION"
          git push
