name: Release

on:
  push:
    paths:
      - 'VERSION'
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    outputs:
      branch_name: ${{ steps.update_formula.outputs.branch_name }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build
        run: cargo build --release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}

      - name: Upload Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/log-inspector
          asset_name: log-inspector
          asset_content_type: application/octet-stream

      - name: Calculate Checksum
        id: checksum
        run: echo "::set-output name=sha256::$(shasum -a 256 target/release/log-inspector | cut -d ' ' -f 1)"

      - name: Update Formula
        id: update_formula
        env:
          VERSION: ${{ steps.version.outputs.version }}
          SHA256: ${{ steps.checksum.outputs.sha256 }}
        run: |
          git fetch origin
          BRANCH_NAME="update-formula-v${VERSION}"
          git checkout -b $BRANCH_NAME origin/main
          
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "# Updated by GitHub Actions on $TIMESTAMP" > Formula/log-inspector.rb.tmp
          cat Formula/log-inspector.rb >> Formula/log-inspector.rb.tmp
          mv Formula/log-inspector.rb.tmp Formula/log-inspector.rb
          
          sed -i '' "s/version \".*\"/version \"$VERSION\"/" Formula/log-inspector.rb
          sed -i '' "s/sha256 \".*\"/sha256 \"$SHA256\"/" Formula/log-inspector.rb
          git add Formula/log-inspector.rb
          git commit -m "Update formula to version $VERSION"
          git push origin $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

  create_pr:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ needs.release.outputs.branch_name }}
          destination_branch: "main"
          pr_title: "Update formula to version ${{ needs.release.outputs.version }}"
          pr_body: "Automated PR to update Homebrew formula"
          pr_label: "automated"

      - name: Enable Auto-merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pr_number }}
          merge-method: squash
