name: Release

on:
#  push:
#    paths:
#      - 'VERSION'
#    branches:
#      - main
  pull_request:
    branches: [ "main" ]
#    paths:
#      - 'VERSION'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        id: version
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Build
        run: cargo build --release
#      - name: Calculate SHA256
#        run: shasum -a 256 target/release/log-inspector | cut -d ' ' -f 1 > sha256.txt
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
      - name: Upload Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/log-inspector
          asset_name: log-inspector
          asset_content_type: application/octet-stream
      - name: Update Formula
        run: |
          export VERSION=$(cat VERSION)
          export SHA256=$(shasum -a 256 target/release/log-inspector | cut -d ' ' -f 1)
          BRANCH_NAME="update-formula-v${VERSION}"
          git fetch origin
          git checkout -b $BRANCH_NAME origin/main
          sed -i '' "s/version \".*\"/version \"$VERSION\"/" Formula/log-inspector.rb
          sed -i '' "s/sha256 \".*\"/sha256 \"$SHA256\"/" Formula/log-inspector.rb
          git add Formula/log-inspector.rb
          git commit -m "Update formula to version $VERSION"
          git push origin $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
  create_pr:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ env.BRANCH_NAME }}
          destination_branch: "main"
          pr_title: "Update formula to version ${{ env.VERSION }}"
          pr_body: "Automated PR to update Homebrew formula"
          pr_label: "automated"
#      - name: Create Pull Request
#        uses: repo-sync/pull-request@v2
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          source_branch: ${{ env.BRANCH_NAME }}
#          destination_branch: "main"
#          pr_title: "Update formula to version ${{ env.VERSION }}"
#          pr_body: "Automated PR to update Homebrew formula"
#          pr_label: "automated"
#      - name: Enable Auto-merge
#        uses: peter-evans/enable-pull-request-automerge@v2
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          pull-request-number: ${{ steps.create-pr.outputs.pr_number }}
#          merge-method: squash
