name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: Build
        run: cargo build --release
      - name: Calculate SHA256
        run: shasum -a 256 target/release/log-inspector | cut -d ' ' -f 1 > sha256.txt
      - name: Update Formula
        run: |
          git checkout main
          SHA256=$(cat sha256.txt)
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i '' "s/version \".*\"/version \"$VERSION\"/" .homebrew/log-inspector.rb
          sed -i '' "s/sha256 \".*\"/sha256 \"$SHA256\"/" .homebrew/log-inspector.rb
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .homebrew/log-inspector.rb
          git commit -m "Update formula to version $VERSION"
          git push origin main
